### ISSUE TITLE
Make the list independent of the Scheduler

### ISSUE THREAD

**Issue by etiennesegonzac** [gaia-components/fast-list#7] opened 2015-08-04 08:24 UTC
By including a fallback inlined "little scheduler" like we did for gaia-dialogs [1].
(With the attachDirect/detachDirect methods shimmed by a simple addEventListener/removeEventListener.)

[1] https://github.com/gaia-components/gaia-dialog/blob/9ddb3c1d3e4b52a09ec9ec373eb977536f0c645d/gaia-dialog.js#L21-L27

**Comment by etiennesegonzac** [comment] 2015-08-04 08:29
Ping @wilsonpage  :)

**Comment by wilsonpage** [comment] 2015-08-04 09:50
Duplicate of #5

**Closed as completed by wilsonpage** 2015-08-04 09:50 UTC
